services:
  client:
    build: ./client
    container_name: web-client
    restart: unless-stopped
    ports:
      - "5173:80" # Frontend runs on port 5173 externally
    networks:
      - mili-resort
    depends_on:
      - server

  server:
    build:
      context: ./server
      args:
        MONGO_URI: mongodb://root:password@mongodb:27017/mili-resort?authSource=admin
    container_name: web-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mili-resort
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:password@mongodb:27017/mili-resort?authSource=admin

    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: my-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - mili-resort
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  mili-resort:
    driver: bridge
