services:
  client:
    build: ./client
    container_name: web-client
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mili-resort
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/miliresorts.in/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/miliresorts.in/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - server

  server:
    build:
      context: ./server
    container_name: web-server
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - mili-resort

    # Load environment variables injected by GitHub Actions
    env_file:
      - .env.production

    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: my-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - mili-resort
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  mili-resort:
    driver: bridge
