# services:
#   client:
#     build: ./client
#     container_name: web-client
#     restart: unless-stopped
#     ports:
#       - "4000:80" # Frontend runs on port 5173 externally
#     networks:
#       - mili-resort
#     depends_on:
#       - server

#   server:
#     build:
#       context: ./server
#     container_name: web-server
#     restart: unless-stopped
#     ports:
#       - "3000:3000"
#     networks:
#       - mili-resort
#     env_file:
#       - .env.production
#     depends_on:
#       - mongodb

#   mongodb:
#     image: mongo:6
#     container_name: my-mongodb
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: password
#     ports:
#       - "27017:27017"
#     networks:
#       - mili-resort
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:

# networks:
#   mili-resort:
#     driver: bridge

services:
client:
  build: ./client
  container_name: web-client
  restart: unless-stopped
  ports:
    - "80:80"
  networks:
    - mili-resort
  depends_on:
    - server

  server:
    build:
      context: ./server
    container_name: web-server
    restart: unless-stopped
    expose:
      - "3000" # expose internally only
    networks:
      - mili-resort
    env_file:
      - .env.production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: my-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - mili-resort
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  mili-resort:
    driver: bridge
