name: Simple VPS Docker Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------------------
      # 1️⃣ Checkout Code
      # --------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # --------------------------------------------------
      # 2️⃣ Send Files to VPS
      # --------------------------------------------------
      - name: Upload project files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./"
          target: "~/mili-resort-backend"
          overwrite: true

      # --------------------------------------------------
      # 3️⃣ Inject .env.production File into Server
      # --------------------------------------------------
      - name: Upload env file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Creating .env.production..."

            cat << 'EOF' > ~/mili-resort-backend/.env.production
            ${{ secrets.ENV_PRODUCTION }}
            EOF

            chmod 600 ~/mili-resort/server/.env.production
            echo ".env.production created."

      # --------------------------------------------------
      # 4️⃣ Deploy Services via Docker Compose
      # --------------------------------------------------
      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/mili-resort-backend

            echo "Stopping old containers..."
            docker compose down || true

            echo "Rebuilding and restarting containers..."
            docker compose up -d --build

            echo "Deployment completed successfully!"
